### PR TITLE
Make util compilable with C++

### PR DESCRIPTION
**Pull request by jokva**
**Task**

Compile `util` with `g++`

**Approach**

Renamed all `util/*.c` files to `.cpp` and compiled with `g++`. Lots of errors, most of them crying about implicit `void*` casts.

As a consequence, some `extern C`s are added and fixed.

The patch isn't warning free with C++, but does compile and tests do work.

**Pre un-WIP checklist**
- [X] Statoil tests pass locally

### CODE REVIEW

**Comment by joakim-hove** [comment]
Will it continue to build and compile with C - or is this a one-way-street?

**Comment by jokva** [comment]
It's still valid C, and it will be for quite a while.

**Comment by jokva** [comment]
Oh, and I should add, the first commit in this series fixes a problem with the `version_*` functions returning non-const pointers to static strings, which is a violation in C++. I don't _think_ it is in C, but it's pretty bad practice anyway.

**Comment by joakim-hove** [comment]
As I understand it: These are changes to the source and header files which allow compilation with a C++ compiler, but the build system will still compile as C?  In that case this should be merged right away - as soon as the merge conflict is resolved.

**Comment by jokva** [comment]
> As I understand it: These are changes to the source and header files which allow compilation with a C++ compiler, but the build system will still compile as C? In that case this should be merged right away - as soon as the merge conflict is resolved.

100% correct.

**Comment by jokva** [comment]
Travis didn't want to restart.

**Pull request merged**
