### PR TITLE
Added requirements.txt for pip install of requirements.

### PR DESCRIPTION
**Pull request by joakim-hove**
**Task**
Use external cwrap + requirements.txt for `pip install`

**Pre un-WIP checklist**
- [ ] Statoil tests pass locally

### CODE REVIEW

**Comment by andreabrambilla** [comment]
Out of curiosity, why numpy ended up in requirements.txt, but pylint and pandas are "manually" installed?

**Comment by pgdr** [comment]
Pandas should pull numpy by itself in conda, pylint is only test-requirement.

**Comment by andreabrambilla** [comment]
I thought so about pylint, but I still don't get the thing with pandas.

Is pandas required only by the tests as well? Or is it actually required by libecl?

**Comment by joakim-hove** [comment]
> Is pandas required only by the tests as well? Or is it actually required by libecl?

The pandas requirement is not for real - that is stale (I think ...)

**Pull request merged**
