### PR TITLE
Add one to timestep if first timestep

### PR DESCRIPTION
**Pull request by pgdr**
**Task**
Debugging `sim_time` and adding documentation, refactored several functions.

(Squash and merge.)

**Pre un-WIP checklist**
- [X] Statoil tests pass locally
- [X] Have completed graphical integration test steps

### CODE REVIEW

**Comment by joakim-hove** [comment]
Hmm  - it has essentially become a linear search?

**Comment by joakim-hove** [comment]
@pgdr : Do you consider this complete?

**Comment by markusdregi** [comment]
@jokva I think we should clean up the commits first. But besides this I do believe that we are done..

**Comment by markusdregi** [comment]
@jokva I've squashed this one now and it should be ready review.

**Pull request merged**
